---
applications:
- name: config
  memory: 512M
  instances: 1
  host: config-${random-word}
  domain: cfapps.io
  path: target/config.jar
  services:
      - bus-rabbitmq
  env:
    SPRING_PROFILES_ACTIVE: cloud
    DEBUG: "true"
    SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/joshlong/bootiful-microservices-config
